name: deploy-command
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cat README.md
          printenv
          echo ${GITHUB_SHA::8}
        env:
          MARKET_CODES: nl*-cte
          SHORT_SHA: ${GITHUB_SHA::8}
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >deployed to ${{ github.event.client_payload.slash_command.args.all }}
          reaction-type: hooray
