name: Deploy command
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for /deploy command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: deploy
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: Validate /deploy command
        if: ${{ !steps.command.outputs.command-arguments }}
        run: exit 0
      - name: Build
        run: echo $MARKET_CODES
        env:
          MARKET_CODES: "${{ steps.command.outputs.command-arguments }}"
