name: Deploy command
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  check-command:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.deploy-command.outputs.arguments }}
    steps:
      - name: Check for /deploy command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: deploy
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - id: deploy-command
        name: Check /deploy command arguments
        run: |
          echo "::set-output name=arguments::${{ steps.command.outputs.command-arguments }}"

  deploy:
    if: needs.deploy-command.outputs.arguments
    runs-on: ubuntu-latest
    needs: check-command
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo $MARKET_CODES
        env:
          MARKET_CODES: ${{ needs.deploy-command.outputs.arguments }}
